name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang clang-tidy valgrind

    - name: Build
      run: |
        clang++ -std=c++17 -o program main.cpp

    - name: Run Clang-Tidy
      run: |
        clang-tidy main.cpp -- -std=c++17

    - name: Run Program
      run: |
        ./program

    - name: Run Valgrind
      run: |
        valgrind --leak-check=full ./program
